version: 1.0.{build}
image: Ubuntu1604
branches:
  # whitelist
  only:
    - master
skip_branch_with_pr: true
install:
- sh: >-
    set -e

    curl https://sh.rustup.rs -sSf > /tmp/sh.rustup.rs

    sh /tmp/sh.rustup.rs -y

    source $HOME/.cargo/env

    export PATH=$PATH:$HOME/.cargo/bin/

    rustup default nightly

build_script:
- sh: >-
    set -e

    ./init_tmp_files.sh

    cargo test

    cargo bench # Test Druzhba

    echo "********ALL DONE*******"
