nodes = \
{'_condition_0': {'condition': '(valid ipv4)',
                  'num_fields': 0,
                  'type': 'condition'},
 '_condition_2': {'condition': '(valid ipv6)',
                  'num_fields': 0,
                  'type': 'condition'},
 'ipv4_routing_ACTION': {'num_fields': 2, 'type': 'action'},
 'ipv4_routing_MATCH': {'key_width': 32, 'type': 'match'},
 'table_2_ACTION': {'num_fields': 1, 'type': 'action'},
 'table_2_MATCH': {'key_width': 32, 'type': 'match'},
 'table_3_ACTION': {'num_fields': 0, 'type': 'action'},
 'table_3_MATCH': {'key_width': 32, 'type': 'match'}}

edges = \
{('_condition_0', '_condition_2'): {'condition': False,
                                    'delay': 0,
                                    'dep_type': 'rmt_successor'},
 ('_condition_0', 'ipv4_routing_ACTION'): {'condition': True,
                                           'delay': 0,
                                           'dep_type': 'rmt_successor'},
 ('_condition_0', 'table_3_ACTION'): {'condition': True,
                                      'delay': 0,
                                      'dep_type': 'rmt_successor'},
 ('_condition_2', 'table_2_ACTION'): {'condition': True,
                                      'delay': 0,
                                      'dep_type': 'rmt_successor'},
 ('ipv4_routing_MATCH', 'ipv4_routing_ACTION'): {'delay': 9,
                                                 'dep_type': 'new_match_to_action'},
 ('table_2_MATCH', 'table_2_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'},
 ('table_3_MATCH', 'table_3_ACTION'): {'delay': 9,
                                       'dep_type': 'new_match_to_action'}}
